// <auto-generated />
using ExamPreparationSystem.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamPreparationSystem.Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519180221_InitialNestedStructure")]
    partial class InitialNestedStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ExamPreparationSystem.Domain.ExamTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("ExamTests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Тест на перевод чисел между 2-й и 10-й системами счисления.",
                            SubjectId = 1,
                            Title = "Вариант №1: Двоичная система"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Тест на работу с большими позиционными системами счисления.",
                            SubjectId = 1,
                            Title = "Вариант №2: Шестнадцатеричная система"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Проверка базовых орфографических правил начальной школы.",
                            SubjectId = 2,
                            Title = "Вариант №1: Правила ЖИ-ШИ и Части речи"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Тест на расстановку знаков препинания и парные согласные.",
                            SubjectId = 2,
                            Title = "Вариант №2: Пунктуация и Согласные"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Простые математические операции, приоритеты действий и поиск X.",
                            SubjectId = 3,
                            Title = "Вариант №1: Арифметика и Уравнения"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Углы фигур, площади и перевод долей в десятичный формат.",
                            SubjectId = 3,
                            Title = "Вариант №2: Геометрия и Дроби"
                        });
                });

            modelBuilder.Entity("ExamPreparationSystem.Domain.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectAnswerIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswerIndex = 1,
                            Options = "11|13|15|9",
                            TestId = 1,
                            Text = "Переведите двоичное число 1101 в десятичную систему:"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswerIndex = 0,
                            Options = "11001|10111|11100|10011",
                            TestId = 1,
                            Text = "Чему равно число 25 из десятичной системы в двоичной?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswerIndex = 1,
                            Options = "4|8|10|16",
                            TestId = 1,
                            Text = "Сколько бит содержится в одном байте?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswerIndex = 2,
                            Options = "16|24|26|30",
                            TestId = 2,
                            Text = "Переведите шестнадцатеричное число 1A в десятичную систему:"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswerIndex = 2,
                            Options = "5|6|7|11",
                            TestId = 2,
                            Text = "Какое число в восьмеричной системе соответствует двоичному числу 111?"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswerIndex = 2,
                            Options = "9|A|G|F",
                            TestId = 2,
                            Text = "Какая цифра отсутствует в шестнадцатеричной системе счисления?"
                        },
                        new
                        {
                            Id = 7,
                            CorrectAnswerIndex = 2,
                            Options = "Машина|Жираф|Жызнь|Шина",
                            TestId = 3,
                            Text = "В каком слове допущена ошибка в правописании сочетаний ЖИ-ШИ?"
                        },
                        new
                        {
                            Id = 8,
                            CorrectAnswerIndex = 1,
                            Options = "Глагол|Имя существительное|Имя прилагательное|Наречие",
                            TestId = 3,
                            Text = "Какая из этих частей речи отвечает на вопросы «Кто?» или «Что?»?"
                        },
                        new
                        {
                            Id = 9,
                            CorrectAnswerIndex = 2,
                            Options = "Признак предмета|Предмет|Действие предмета|Количество",
                            TestId = 3,
                            Text = "Что обозначает глагол как часть речи?"
                        },
                        new
                        {
                            Id = 10,
                            CorrectAnswerIndex = 3,
                            Options = "Нос|Лес|Класс|Арбуз",
                            TestId = 4,
                            Text = "Укажите слово, в котором на конце пишется парная согласная 'З', а слышится 'С':"
                        },
                        new
                        {
                            Id = 11,
                            CorrectAnswerIndex = 1,
                            Options = "Запятая|Точка|Вопросительный знак|Двоеточие",
                            TestId = 4,
                            Text = "Какой знак препинания ставится в конце стандартного повествовательного предложения?"
                        },
                        new
                        {
                            Id = 12,
                            CorrectAnswerIndex = 0,
                            Options = "В именах собственных|В конце строки|Перед запятой|В длинных словах",
                            TestId = 4,
                            Text = "Где всегда пишется большая (прописная) буква?"
                        },
                        new
                        {
                            Id = 13,
                            CorrectAnswerIndex = 1,
                            Options = "8|6|4|5",
                            TestId = 5,
                            Text = "Вычислите значение выражения: 2 + 2 * 2"
                        },
                        new
                        {
                            Id = 14,
                            CorrectAnswerIndex = 2,
                            Options = "10|20|25|50",
                            TestId = 5,
                            Text = "Чему равен квадрат числа 5 (5 во второй степени)?"
                        },
                        new
                        {
                            Id = 15,
                            CorrectAnswerIndex = 2,
                            Options = "2|3|4|9",
                            TestId = 5,
                            Text = "Решите уравнение: 3x = 12. Чему равен x?"
                        },
                        new
                        {
                            Id = 16,
                            CorrectAnswerIndex = 1,
                            Options = "0.4|0.25|0.5|0.04",
                            TestId = 6,
                            Text = "Какое число получится, если 1/4 перевести в десятичную дробь?"
                        },
                        new
                        {
                            Id = 17,
                            CorrectAnswerIndex = 1,
                            Options = "90 градусов|180 градусов|360 градусов|270 градусов",
                            TestId = 6,
                            Text = "Чему равна сумма углов в абсолютно любом треугольнике?"
                        },
                        new
                        {
                            Id = 18,
                            CorrectAnswerIndex = 2,
                            Options = "Ромб|Треугольник|Квадрат|Трапеция",
                            TestId = 6,
                            Text = "Как называется геометрическая фигура, у которой все четыре стороны равны, а углы прямые?"
                        });
                });

            modelBuilder.Entity("ExamPreparationSystem.Domain.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Системы счисления и основы кодирования данных.",
                            Name = "💻 Информатика"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Орфография, пунктуация и культура речи.",
                            Name = "📚 Русский язык"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Арифметика, уравнения и основы геометрии.",
                            Name = "📐 Математика"
                        });
                });

            modelBuilder.Entity("ExamPreparationSystem.Domain.ExamTest", b =>
                {
                    b.HasOne("ExamPreparationSystem.Domain.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamPreparationSystem.Domain.Question", b =>
                {
                    b.HasOne("ExamPreparationSystem.Domain.ExamTest", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
