// <auto-generated />
using ExamPreparationSystem.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamPreparationSystem.Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ExamPreparationSystem.Domain.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectAnswerIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswerIndex = 1,
                            Options = "11|13|15|9",
                            SubjectId = 1,
                            Text = "Переведите двоичное число 1101 в десятичную систему счисления:"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswerIndex = 0,
                            Options = "11001|10111|11100|10011",
                            SubjectId = 1,
                            Text = "Чему равно число 25 из десятичной системы в двоичной?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswerIndex = 2,
                            Options = "16|24|26|30",
                            SubjectId = 1,
                            Text = "Переведите шестнадцатеричное число 1A в десятичную систему:"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswerIndex = 2,
                            Options = "5|6|7|11",
                            SubjectId = 1,
                            Text = "Какое число в восьмеричной системе соответствует двоичному числу 111?"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswerIndex = 1,
                            Options = "4|8|10|16",
                            SubjectId = 1,
                            Text = "Сколько бит содержится в одном байте?"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswerIndex = 2,
                            Options = "Машина|Жираф|Жызнь|Шина",
                            SubjectId = 2,
                            Text = "В каком слове допущена ошибка в правописании сочетаний ЖИ-ШИ?"
                        },
                        new
                        {
                            Id = 7,
                            CorrectAnswerIndex = 1,
                            Options = "Глагол|Имя существительное|Имя прилагательное|Наречие",
                            SubjectId = 2,
                            Text = "Какая из этих частей речи отвечает на вопросы «Кто?» или «Что?»?"
                        },
                        new
                        {
                            Id = 8,
                            CorrectAnswerIndex = 3,
                            Options = "Нос|Лес|Класс|Арбуз",
                            SubjectId = 2,
                            Text = "Укажите слово, в котором на конце пишется парная согласная 'З', а слышится 'С':"
                        },
                        new
                        {
                            Id = 9,
                            CorrectAnswerIndex = 1,
                            Options = "Город|Москва|Река|Книга",
                            SubjectId = 2,
                            Text = "Какое слово всегда пишется с большой (прописной) буквы в любом месте предложения?"
                        },
                        new
                        {
                            Id = 10,
                            CorrectAnswerIndex = 1,
                            Options = "Запятая|Точка|Вопросительный знак|Двоеточие",
                            SubjectId = 2,
                            Text = "Какой знак препинания ставится в конце стандартного повествовательного предложения?"
                        },
                        new
                        {
                            Id = 11,
                            CorrectAnswerIndex = 1,
                            Options = "8|6|4|5",
                            SubjectId = 3,
                            Text = "Вычислите значение выражения: 2 + 2 * 2"
                        },
                        new
                        {
                            Id = 12,
                            CorrectAnswerIndex = 2,
                            Options = "10|20|25|50",
                            SubjectId = 3,
                            Text = "Чему равен квадрат числа 5 (5 во второй степени)?"
                        },
                        new
                        {
                            Id = 13,
                            CorrectAnswerIndex = 1,
                            Options = "0.4|0.25|0.5|0.04",
                            SubjectId = 3,
                            Text = "Какое число получится, если 1/4 (одну четвертую) перевести в десятичную дробь?"
                        },
                        new
                        {
                            Id = 14,
                            CorrectAnswerIndex = 1,
                            Options = "90 градусов|180 градусов|360 градусов|270 градусов",
                            SubjectId = 3,
                            Text = "Чему равна сумма углов в абсолютно любом треугольнике?"
                        },
                        new
                        {
                            Id = 15,
                            CorrectAnswerIndex = 2,
                            Options = "2|3|4|9",
                            SubjectId = 3,
                            Text = "Решите простейшее уравнение: 3x = 12. Чему равен x?"
                        });
                });

            modelBuilder.Entity("ExamPreparationSystem.Domain.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Перевод чисел между двоичной, восьмеричной, десятичной и шестнадцатеричной системами.",
                            Name = "💻 Информатика: Системы счисления"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Простейшие правила правописания, части речи и знаки препинания.",
                            Name = "📚 Русский язык: Базовая орфография"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Простые арифметические действия, дроби и основы геометрии.",
                            Name = "📐 Математика: Базовый счет"
                        });
                });

            modelBuilder.Entity("ExamPreparationSystem.Domain.Question", b =>
                {
                    b.HasOne("ExamPreparationSystem.Domain.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
